apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ .Chart.Name }}-fs
  namespace: {{ .Release.Namespace }}
spec:
  metadataPool:
    replicated:
      size: {{ .Values.storage.nodes }}
  dataPools:
    - replicated:
        size: {{ .Values.storage.nodes }}
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true